#!/bin/sh
#
# Copyright (C) 2004 Jimmy Olsen
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation; version 2 dated June,
# 1991.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA  02111-1307, USA.
#
#
# Plugin to monitor httping times
#
# Parameters:
#
# 	httping_args      - Arguments to httping (default "-c 2")
# 	httping_args2     - Arguments after the host name (required for Solaris)
# 	httping           - Ping program to use
# 	host           - Host to httping
#
# Arguments for Solaris:
#      httping_args      -s
#      httping_args2     56 2
#
#%# family=manual

file_host=`basename $0 | sed 's/^httping_//g'`
host=${host:-${file_host:-www.google.com}}

if [ "$1" = "config" ]; then
	echo graph_title HTTP connection times to $host
	echo 'graph_args --base 1000 -l 0'
	echo 'graph_vlabel seconds'
	echo 'graph_category network'
	echo 'graph_info This graph shows HTTP statistics.'
	echo "httping.label $host"
	echo "httping.info HTTP statistics for $host."
	echo 'httping.draw LINE2'
	echo 'failed.label connects failed'
	echo 'failed.graph no'
	exit 0
fi


${httping:-httping} ${httping_args:-'-c 2'} ${host} ${httping_args2} | perl -n -e 'print "httping.value ", $1 / 1000, "\n" if m@min/avg/max.*\s\d+(?:\.\d+)?/(\d+(?:\.\d+)?)/\d+(?:\.\d+)?@; print "failed.value $1\n" if /(\d+)% failed/;'

