#!/usr/bin/env perl
#
# Magic markers:
#%# family=contrib
#%# capabilities=

use strict;
use warnings;

#use lib $ENV{'MUNIN_LIBDIR'};
#use Munin::Plugin;

my $logfile = '/var/log/nginx/cache-access.log';
my $logtail = '/usr/local/sbin/logtail';
my $offsetfile = "/usr/local/var/munin/plugin-state/nginx_cache_efficiency.offset";

my $cmd = (defined($ARGV[0])) ? $ARGV[0] : '';

(defined($ENV{'logfile'})) and $logfile = $ENV{'logfile'};
(defined($ENV{'logtail'})) and $logtail = $ENV{'logtail'};

if ($cmd eq 'config') {
	print("graph_title NGINX Cache Efficiency\n");
	print "graph_category Nginx\n";
	print("graph_vlabel This graph shows the cache efficiency\n");
        print("graph_args --lower-limit 0 --upper-limit 100\n");
        print("graph_vlabel %\n");
        print("request.label total request hits\n");
        print("byte.label total byte hits\n");

	exit(0);
}

open(LOG, "$logtail -f $logfile -o $offsetfile|");

my @lines = <LOG>;
close (LOG);

my $requests = 0;
my $bytes = 0;
my $hits = 0;
my $counts = 0;
my $cached = 0;

foreach (@lines) {
	chomp;
	$counts++;
	# 21/Jan/2010:12:50:12 +0300 HIT "GET /4/user_48/1084/1084323.jpg?20091206201902 HTTP/1.0" 200 1342
	if ( /^\S+\s.\d{4}\s(\S+)\s\"[^"]+\"\s200\s(\d+)/) {
		my($status, $size) = ($1, $2);
		if ($status =~ /HIT/ ) { 
			$hits++; 
			$cached += $size;
		}
		$requests++;
		$bytes += $size
	}
	
}

my $request_hits = int($hits   *100 / $requests);
my $byte_hits    = int($cached *100 / $bytes);

print "request.value $request_hits\n";
print "byte.value $byte_hits\n";

exit(0);
