#! /usr/bin/env perl
#
# Magic markers:
#%# family=contrib
#%# capabilities=

use strict;
use warnings;

#use lib $ENV{'MUNIN_LIBDIR'};
#use Munin::Plugin;

use POSIX qw(strftime);

my $logfile = '/var/log/nginx/post-access.log';
my $logtail = '/usr/local/sbin/logtail';
#my $offsetfile = "/tmp/offset";
my $offsetfile = "/var/tmp/nginx-post.offset";

my $cmd = (defined($ARGV[0])) ? $ARGV[0] : '';

(defined($ENV{'logfile'})) and $logfile = $ENV{'logfile'};
(defined($ENV{'logtail'})) and $logtail = $ENV{'logtail'};

if ($cmd eq 'config') {
	print("graph_title NGINX POST requests \n");
	print("graph_args --lower-limit 0\n");
#	print("graph_args --upper-limit 200\n");
	print("graph_scale no\n");
	print "graph_category Nginx\n";
	print("graph_vlabel POST requests \n");

	print("post.label post\n");
	print("post.type GAUGE\n");
	print("post.draw LINE2\n");

	exit(0);
}

open(LOG, "$logtail -f $logfile -o $offsetfile|");
my @lines = <LOG>;
close (LOG);

my $post_requests = grep( /POST/, @lines);

print "post.value ". $post_requests  ."\n";

exit(0);
