#! /usr/bin/env perl
#
# Magic markers:
#%# family=contrib
#%# capabilities=

use strict;
use warnings;

#use lib $ENV{'MUNIN_LIBDIR'};
#use Munin::Plugin;

use POSIX qw(strftime);

my $logfile = '/usr/mem_disk/upstream-access.log';
#my $logfile = '/tmp/1.txt';
my $logtail = '/usr/local/sbin/logtail';
#my $offsetfile = "/tmp/offset2";
my $offsetfile = "/usr/local/var/munin/plugin-state/munin-upstream-slow-queries.offset";

my $cmd = (defined($ARGV[0])) ? $ARGV[0] : '';

(defined($ENV{'logfile'})) and $logfile = $ENV{'logfile'};
(defined($ENV{'logtail'})) and $logtail = $ENV{'logtail'};

if ($cmd eq 'config') {
	print("graph_title NGINX upstream slowqueries count \n");
#	print("graph_args --lower-limit 0\n");
#	print("graph_args --upper-limit 200\n");
#	print("graph_scale no\n");
	print "graph_category Nginx\n";
	print("graph_vlabel slow queries count\n");

	print("cache1.label cache1\n");
	print("cache1.type GAUGE\n");
	print("cache1.draw LINE2\n");

	print("cache2.label cache2\n");
	print("cache2.type GAUGE\n");
	print("cache2.draw LINE2\n");

	print("cache3.label cache3\n");
	print("cache3.type GAUGE\n");
	print("cache3.draw LINE2\n");

	print("cache4.label cache4\n");
	print("cache4.type GAUGE\n");
	print("cache4.draw LINE2\n");

	print("cache5.label cache5\n");
	print("cache5.type GAUGE\n");
	print("cache5.draw LINE2\n");



	exit(0);
}

open(LOG, "$logtail -f $logfile -o $offsetfile|");
my @lines = <LOG>;
close (LOG);

my %queries_count = ('10.13.177.69'  => 0,
		     '10.13.177.70'  => 0,
		     '10.13.177.71'  => 0,
		     '10.13.177.116' => 0,
		     '10.13.177.118' => 0
);

foreach (@lines) {
	chomp;
	my($ip, $uri, $rt) = split(/\s?,\s?/, $_);
	next until (defined $rt && $rt ne "-");
	$ip =~ s/:[0-9]+//;

	$queries_count{$ip}++ if ($rt > 2);
}
print "cache1.value ". $queries_count{'10.13.177.69'}  ."\n";
print "cache2.value ". $queries_count{'10.13.177.70'}  ."\n";
print "cache3.value ". $queries_count{'10.13.177.71'}  ."\n";
print "cache4.value ". $queries_count{'10.13.177.116'} ."\n";
print "cache5.value ". $queries_count{'10.13.177.118'} ."\n";

exit(0);
